### ISSUE TITLE
While running the code grunt does not fount

### ISSUE THREAD

**Issue by ansulagrawal** [AshBardhan/memefy-this#15]
After doing yarn install and npm install
Grunt does not found 
![image](https://user-images.githubusercontent.com/55939700/153502478-70c1fdbf-36d7-4fab-8a9b-5a40b1a27bcf.png)

**Comment by AshBardhan** [comment]
Seems more like a 'grunt' dependency compatible issue as this repo hasn't been updated for a long time. I will look into this shortly.
