### ISSUE TITLE
Add Loader for Demo Video

### ISSUE THREAD

**Issue by AshBardhan** [AshBardhan/memefy-this#2]
As suggested by [Rachit](https://github.com/rachitGulati)

**Comment by rachitGulati** [comment]
I have opened a pull request for the same.
https://github.com/AshBardhan/memefy-this/pull/3/commits

**Comment by AshBardhan** [comment]
Updated and refactored the SVG code.

**Comment by AshBardhan** [comment]
Closing this issue
